print('x:')
x = input()
print('*a:')
a = input()
print('/b:')
b = input()
print('+c:')
c = input()
print('-d:')
d = input()
print( str(x) + ' * ' + str(a) + ' / ' + str(b) + ' + ' + str(c) + ' - ' + str(d) + ' = ', end='')
print(int(x) * int(a) / int(b) + int(c) - int(d))
